spring.application.name=wasgames

spring.datasource.url=jdbc:postgresql://localhost:5432/wasgames
spring.datasource.username=wasgames_user
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
